#!/usr/bin/env python
# INSTRUCTIONS:
# USE THIS FILE TO OVERRIDE THE MAIN SETTINGS FILE
# RENAME FILE TO constants_user.py
# DON'T FORGET TO REGENERATE ANY VARIABLES THAT DERIVE FROM THE ONES YOU ARE CHANGING
from anknotes.constants_default import *

# BEGIN OVERRIDES HERE:
EVERNOTE.API.IS_SANDBOXED = True
EVERNOTE.UPLOAD.VALIDATION.AUTOMATED = False
EVERNOTE.UPLOAD.ENABLED = False