# INSTRUCTIONS:
# USE THIS FILE TO OVERRIDE THE MAIN SETTINGS FILE
# PREFIX ALL SETTINGS WITH THE constants MODULE REFERENCE AS SHOWN BELOW:
# DON'T FORGET TO REGENERATE ANY VARIABLES THAT DERIVE FROM THE ONES YOU ARE CHANGING

from anknotes import constants
# constants.EVERNOTE.API.IS_SANDBOXED = True
# constants.SETTINGS.EVERNOTE.AUTH_TOKEN = 'anknotesEvernoteAuthToken_' + constants.EVERNOTE.API.CONSUMER_KEY + (
		# "_SANDBOX" if constants.EVERNOTE.API.IS_SANDBOXED else "")
