#
# Autogenerated by Thrift Compiler
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:new_style
#

from anknotes.thrift.Thrift import TType, TMessageType, TException, TApplicationException

from anknotes.thrift.transport import TTransport
from anknotes.thrift.protocol import TBinaryProtocol, TProtocol
try:
  from anknotes.thrift.protocol import fastbinary
except:
  fastbinary = None


